version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: breeze_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=breeze-db
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
  db:
    image: postgres
    container_name: breeze_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=breeze-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    volumes:
      - dev-db:/var/lib/pgsql
  nginx:
    image: nginx:alpine
    container_name: breeze_nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  dev-db:
    driver: local
